spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=uun_index_companies
    password: 123
    username: ondrejbruha
  application:
    name: index-of-companies
  api-url:
    get-by-ico-url: https://ares.gov.cz/ekonomicke-subjekty-v-be/rest/ekonomicke-subjekty

